### ISSUE TITLE
FreeBSD-11.2

### ISSUE THREAD

**Issue by odhiambo** [grosjo/fts-xapian#5] opened 2019-01-14 18:16 UTC
[root@waridi /opt/dovecot2.3/etc/dovecot/conf.d]# /opt/dovecot2.3/bin/doveadm index -u accounts@mydomain.com -q \*
doveadm(accounts@mydomain.com): Panic: file mailbox-list.c: line 1244 (mailbox_list_try_mkdir_root): assertion failed: (str_begins(path, root_dir))
Abort trap

**Comment by grosjo** [comment] 2019-01-14 20:09
Hi
You need to configure Home Directories : https://wiki.dovecot.org/VirtualUsers/Home

PLease post your log ifle where it says something similar to :
Jan 14 20:09:01 gjserver dovecot[28380]: indexer-worker(admin@grosjo.net)<29268><TS32Al3sPFwQdAAA0thIag:qNaQBF3sPFxUcgAA0thIag>: FTS Xapian: Partial=2, Full=20 DB_PATH=/data/mail/grosjo.net/admin/xapian-indexes

**Comment by odhiambo** [comment] 2019-01-14 22:03
On Mon, 14 Jan 2019 at 23:09, Joan Moreau <notifications@github.com> wrote:

> Hi
> You need to configure Home Directories :
> https://wiki.dovecot.org/VirtualUsers/Home
>
These are virtual users. So
mail_location =
maildir:/var/spool/virtual/%d/%n/Maildir:INDEX=/var/spool/virtual/indexes/%d/%1n/%n

And here is the home:
mysql>  SELECT pop as home, smtp FROM users WHERE username like 'dns%';
+--------------------------------------+----------------------------------------------+
| home                                 | smtp
           |
+--------------------------------------+----------------------------------------------+
| /var/spool/virtual/mydomain.com/accounts | /var/spool/virtual/
mydomain.com/accounts/Maildir |
+--------------------------------------+----------------------------------------------+


> PLease post your log ifle where it says something similar to :
> Jan 14 20:09:01 gjserver dovecot[28380]: indexer-worker(admin@grosjo.net)<29268>TS32Al3sPFwQdAAA0thIag:qNaQBF3sPFxUcgAA0thIag:
> FTS Xapian: Partial=2, Full=20 DB_PATH=/data/mail/
> grosjo.net/admin/xapian-indexes
>
I don't have such a log entry.
[root@waridi /opt/dovecot2.3/etc/dovecot/conf.d]#
/opt/dovecot2.3/bin/doveadm index -u accounts@mydomain.com -q *
doveadm(accounts@mydomain.com): Panic: file mailbox-list.c: line 1244
(mailbox_list_try_mkdir_root): assertion failed: (str_begins(path,
root_dir))
Abort trap


-- 
Best regards,
Odhiambo WASHINGTON,
Nairobi,KE
+254 7 3200 0004/+254 7 2274 3223
"Oh, the cruft.", grep ^[^#] :-)

**Comment by grosjo** [comment] 2019-01-15 13:25
Can you send the mentioned log above ? (where there are the full and partial parameter and the DB_PATH )

**Comment by grosjo** [comment] 2019-01-16 09:26
Duplicate of issue #4

**Closed as completed by grosjo** 2019-01-16 09:26 UTC
