### ISSUE TITLE
dovecot-fts-xapian panics after dovecot upgrade to 2.3.17

### ISSUE THREAD

**Issue by jurajlutter** [grosjo/fts-xapian#100] opened 2021-11-02 18:36 UTC
Hi,

an user at FreeBSD bug tracker reports:

```
Dovecot LMTP panics and won't deliver mail after I updated to dovecot-fts-xapian-1.4.13_2 combined with dovecot-2.3.17_1 and dovecot-pigeonhole-0.5.17 today. The error:

Nov  2 18:08:00 mail dovecot[37656]: lmtp(user@host)<37666><yHG7K3BwgWEikwAA0J78UA>: Panic: file array.c: line 10 (array_idx_modifiable_i): assertion failed: (idx < array->buffer->used / array->element_size)
Nov  2 18:08:00 mail dovecot[37656]: lmtp(user@host)<37666><yHG7K3BwgWEikwAA0J78UA>: Fatal: master: service(lmtp): child 37666 killed with signal 6 (core not dumped - https://dovecot.org/bugreport.html#coredumps - set service lmtp { drop_priv_before_exec=yes })
```

Otherwise unchanged configuration. I did the pkg upgrade, restarted my mail jail and these errors started popping up. Managed to work around it for now by completely disabling FTS.

For reference see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259616

coredumps are not yet available, will keep you posted as soon as OP delivers them.

**Comment by grosjo** [comment] 2021-11-02 21:38
The problem is known, latest git shall remove the coredump

THe issue is that Dovecot 2.3.17 chanegs drastically its api without notice.

Still some memory leaks exists

@cmouse please help. need really a fix on this

**Comment by grosjo** [comment] 2021-11-04 14:27
Closed as an exact duplicate of https://github.com/grosjo/fts-xapian/issues/99

**Closed as completed by grosjo** 2021-11-04 14:27 UTC
